name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Cache Ollama
        id: cache-ollama
        uses: actions/cache@v3
        with:
          path: ollama
          key: ${{ runner.os }}-ollama

      - name: Build ollama
        if: steps.cache-ollama.outputs.cache-hit != 'true'
        run: git clone --recursive https://github.com/jmorganca/ollama && cd ollama && go generate ./... && go build -v

      - name: Test the ollama executable
        run: ollama/ollama --help

      - name: Run ollama in the background
        run: ollama/ollama serve &

      - name: Pull an image
        run: ollama/ollama pull llama2:chat

      - name: Generate a poem
        run: ollama/ollama run llama2:chat "$(cat prompt.txt)"
